/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as LegalRouteRouteImport } from './routes/_legal/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminWorkspacesIndexRouteImport } from './routes/admin/workspaces/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminKbIndexRouteImport } from './routes/admin/kb/index'
import { Route as AdminEmailIndexRouteImport } from './routes/admin/email/index'
import { Route as AdminDocsIndexRouteImport } from './routes/admin/docs/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminContentIndexRouteImport } from './routes/admin/content/index'
import { Route as AdminContactsIndexRouteImport } from './routes/admin/contacts/index'
import { Route as AdminComponentsIndexRouteImport } from './routes/admin/components/index'
import { Route as AdminAccountIndexRouteImport } from './routes/admin/account/index'
import { Route as PublicUnsubscribeIndexRouteImport } from './routes/_public/unsubscribe/index'
import { Route as PublicServicesIndexRouteImport } from './routes/_public/services/index'
import { Route as PublicPortfolioIndexRouteImport } from './routes/_public/portfolio/index'
import { Route as PublicContactIndexRouteImport } from './routes/_public/contact/index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as PublicAboutIndexRouteImport } from './routes/_public/about/index'
import { Route as LegalPrivacyPolicyIndexRouteImport } from './routes/_legal/privacy-policy/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as AuthAccountIndexRouteImport } from './routes/_auth/account/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminMediaAssetIdRouteImport } from './routes/admin/media/$assetId'
import { Route as AdminKbSlugRouteImport } from './routes/admin/kb/$slug'
import { Route as PublicPortfolioSlugRouteImport } from './routes/_public/portfolio/$slug'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog/$slug'
import { Route as AuthAccountNotificationsRouteImport } from './routes/_auth/account/notifications'
import { Route as AdminWorkspacesPlatformIndexRouteImport } from './routes/admin/workspaces/platform/index'
import { Route as AdminWorkspacesOperationsIndexRouteImport } from './routes/admin/workspaces/operations/index'
import { Route as AdminWorkspacesContentIndexRouteImport } from './routes/admin/workspaces/content/index'
import { Route as AdminDocsPhasesIndexRouteImport } from './routes/admin/docs/phases/index'
import { Route as AdminDocsArchitectureIndexRouteImport } from './routes/admin/docs/architecture/index'
import { Route as AdminDocsAdrIndexRouteImport } from './routes/admin/docs/adr/index'
import { Route as AdminContentPostsIndexRouteImport } from './routes/admin/content/posts/index'
import { Route as AdminComponentsUiIndexRouteImport } from './routes/admin/components/ui/index'
import { Route as AdminComponentsNavigationIndexRouteImport } from './routes/admin/components/navigation/index'
import { Route as AdminComponentsMarketingIndexRouteImport } from './routes/admin/components/marketing/index'
import { Route as ApiEmailWebhooksResendRouteImport } from './routes/api/email/webhooks/resend'
import { Route as AdminContentPostsNewRouteImport } from './routes/admin/content/posts/new'
import { Route as AdminContentPostsIdRouteImport } from './routes/admin/content/posts/$id'
import { Route as AdminWorkspacesPlatformDocsIndexRouteImport } from './routes/admin/workspaces/platform/docs/index'
import { Route as AdminWorkspacesPlatformComponentsIndexRouteImport } from './routes/admin/workspaces/platform/components/index'
import { Route as AdminWorkspacesOperationsUsersIndexRouteImport } from './routes/admin/workspaces/operations/users/index'
import { Route as AdminWorkspacesOperationsSettingsIndexRouteImport } from './routes/admin/workspaces/operations/settings/index'
import { Route as AdminWorkspacesOperationsEmailIndexRouteImport } from './routes/admin/workspaces/operations/email/index'
import { Route as AdminWorkspacesOperationsDashboardIndexRouteImport } from './routes/admin/workspaces/operations/dashboard/index'
import { Route as AdminWorkspacesOperationsContactsIndexRouteImport } from './routes/admin/workspaces/operations/contacts/index'
import { Route as AdminWorkspacesOperationsAccountIndexRouteImport } from './routes/admin/workspaces/operations/account/index'
import { Route as AdminWorkspacesContentPostsIndexRouteImport } from './routes/admin/workspaces/content/posts/index'
import { Route as AdminWorkspacesContentMediaIndexRouteImport } from './routes/admin/workspaces/content/media/index'
import { Route as AdminWorkspacesContentKbIndexRouteImport } from './routes/admin/workspaces/content/kb/index'
import { Route as AdminWorkspacesOperationsUsersUserIdRouteImport } from './routes/admin/workspaces/operations/users/$userId'
import { Route as AdminWorkspacesContentPostsNewRouteImport } from './routes/admin/workspaces/content/posts/new'
import { Route as AdminWorkspacesContentPostsIdRouteImport } from './routes/admin/workspaces/content/posts/$id'
import { Route as AdminWorkspacesContentMediaAssetIdRouteImport } from './routes/admin/workspaces/content/media/$assetId'
import { Route as AdminWorkspacesContentKbSlugRouteImport } from './routes/admin/workspaces/content/kb/$slug'
import { Route as AdminWorkspacesPlatformDocsPhasesIndexRouteImport } from './routes/admin/workspaces/platform/docs/phases/index'
import { Route as AdminWorkspacesPlatformDocsArchitectureIndexRouteImport } from './routes/admin/workspaces/platform/docs/architecture/index'
import { Route as AdminWorkspacesPlatformDocsAdrIndexRouteImport } from './routes/admin/workspaces/platform/docs/adr/index'
import { Route as AdminWorkspacesPlatformComponentsUiIndexRouteImport } from './routes/admin/workspaces/platform/components/ui/index'
import { Route as AdminWorkspacesPlatformComponentsNavigationIndexRouteImport } from './routes/admin/workspaces/platform/components/navigation/index'
import { Route as AdminWorkspacesPlatformComponentsMarketingIndexRouteImport } from './routes/admin/workspaces/platform/components/marketing/index'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminWorkspacesIndexRoute = AdminWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKbIndexRoute = AdminKbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailIndexRoute = AdminEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocsIndexRoute = AdminDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactsIndexRoute = AdminContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComponentsIndexRoute = AdminComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountIndexRoute = AdminAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicUnsubscribeIndexRoute = PublicUnsubscribeIndexRouteImport.update({
  id: '/unsubscribe/',
  path: '/unsubscribe/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPortfolioIndexRoute = PublicPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactIndexRoute = PublicContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutIndexRoute = PublicAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const LegalPrivacyPolicyIndexRoute = LegalPrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => LegalRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAccountIndexRoute = AuthAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaAssetIdRoute = AdminMediaAssetIdRouteImport.update({
  id: '/media/$assetId',
  path: '/media/$assetId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKbSlugRoute = AdminKbSlugRouteImport.update({
  id: '/kb/$slug',
  path: '/kb/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicPortfolioSlugRoute = PublicPortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthAccountNotificationsRoute =
  AuthAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AdminWorkspacesPlatformIndexRoute =
  AdminWorkspacesPlatformIndexRouteImport.update({
    id: '/workspaces/platform/',
    path: '/workspaces/platform/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesOperationsIndexRoute =
  AdminWorkspacesOperationsIndexRouteImport.update({
    id: '/workspaces/operations/',
    path: '/workspaces/operations/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesContentIndexRoute =
  AdminWorkspacesContentIndexRouteImport.update({
    id: '/workspaces/content/',
    path: '/workspaces/content/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDocsPhasesIndexRoute = AdminDocsPhasesIndexRouteImport.update({
  id: '/docs/phases/',
  path: '/docs/phases/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocsArchitectureIndexRoute =
  AdminDocsArchitectureIndexRouteImport.update({
    id: '/docs/architecture/',
    path: '/docs/architecture/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDocsAdrIndexRoute = AdminDocsAdrIndexRouteImport.update({
  id: '/docs/adr/',
  path: '/docs/adr/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentPostsIndexRoute = AdminContentPostsIndexRouteImport.update({
  id: '/content/posts/',
  path: '/content/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComponentsUiIndexRoute = AdminComponentsUiIndexRouteImport.update({
  id: '/components/ui/',
  path: '/components/ui/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComponentsNavigationIndexRoute =
  AdminComponentsNavigationIndexRouteImport.update({
    id: '/components/navigation/',
    path: '/components/navigation/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminComponentsMarketingIndexRoute =
  AdminComponentsMarketingIndexRouteImport.update({
    id: '/components/marketing/',
    path: '/components/marketing/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const ApiEmailWebhooksResendRoute = ApiEmailWebhooksResendRouteImport.update({
  id: '/api/email/webhooks/resend',
  path: '/api/email/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentPostsNewRoute = AdminContentPostsNewRouteImport.update({
  id: '/content/posts/new',
  path: '/content/posts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentPostsIdRoute = AdminContentPostsIdRouteImport.update({
  id: '/content/posts/$id',
  path: '/content/posts/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWorkspacesPlatformDocsIndexRoute =
  AdminWorkspacesPlatformDocsIndexRouteImport.update({
    id: '/workspaces/platform/docs/',
    path: '/workspaces/platform/docs/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesPlatformComponentsIndexRoute =
  AdminWorkspacesPlatformComponentsIndexRouteImport.update({
    id: '/workspaces/platform/components/',
    path: '/workspaces/platform/components/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesOperationsUsersIndexRoute =
  AdminWorkspacesOperationsUsersIndexRouteImport.update({
    id: '/workspaces/operations/users/',
    path: '/workspaces/operations/users/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesOperationsSettingsIndexRoute =
  AdminWorkspacesOperationsSettingsIndexRouteImport.update({
    id: '/workspaces/operations/settings/',
    path: '/workspaces/operations/settings/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesOperationsEmailIndexRoute =
  AdminWorkspacesOperationsEmailIndexRouteImport.update({
    id: '/workspaces/operations/email/',
    path: '/workspaces/operations/email/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesOperationsDashboardIndexRoute =
  AdminWorkspacesOperationsDashboardIndexRouteImport.update({
    id: '/workspaces/operations/dashboard/',
    path: '/workspaces/operations/dashboard/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesOperationsContactsIndexRoute =
  AdminWorkspacesOperationsContactsIndexRouteImport.update({
    id: '/workspaces/operations/contacts/',
    path: '/workspaces/operations/contacts/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesOperationsAccountIndexRoute =
  AdminWorkspacesOperationsAccountIndexRouteImport.update({
    id: '/workspaces/operations/account/',
    path: '/workspaces/operations/account/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesContentPostsIndexRoute =
  AdminWorkspacesContentPostsIndexRouteImport.update({
    id: '/workspaces/content/posts/',
    path: '/workspaces/content/posts/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesContentMediaIndexRoute =
  AdminWorkspacesContentMediaIndexRouteImport.update({
    id: '/workspaces/content/media/',
    path: '/workspaces/content/media/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesContentKbIndexRoute =
  AdminWorkspacesContentKbIndexRouteImport.update({
    id: '/workspaces/content/kb/',
    path: '/workspaces/content/kb/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesOperationsUsersUserIdRoute =
  AdminWorkspacesOperationsUsersUserIdRouteImport.update({
    id: '/workspaces/operations/users/$userId',
    path: '/workspaces/operations/users/$userId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesContentPostsNewRoute =
  AdminWorkspacesContentPostsNewRouteImport.update({
    id: '/workspaces/content/posts/new',
    path: '/workspaces/content/posts/new',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesContentPostsIdRoute =
  AdminWorkspacesContentPostsIdRouteImport.update({
    id: '/workspaces/content/posts/$id',
    path: '/workspaces/content/posts/$id',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesContentMediaAssetIdRoute =
  AdminWorkspacesContentMediaAssetIdRouteImport.update({
    id: '/workspaces/content/media/$assetId',
    path: '/workspaces/content/media/$assetId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesContentKbSlugRoute =
  AdminWorkspacesContentKbSlugRouteImport.update({
    id: '/workspaces/content/kb/$slug',
    path: '/workspaces/content/kb/$slug',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesPlatformDocsPhasesIndexRoute =
  AdminWorkspacesPlatformDocsPhasesIndexRouteImport.update({
    id: '/workspaces/platform/docs/phases/',
    path: '/workspaces/platform/docs/phases/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesPlatformDocsArchitectureIndexRoute =
  AdminWorkspacesPlatformDocsArchitectureIndexRouteImport.update({
    id: '/workspaces/platform/docs/architecture/',
    path: '/workspaces/platform/docs/architecture/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesPlatformDocsAdrIndexRoute =
  AdminWorkspacesPlatformDocsAdrIndexRouteImport.update({
    id: '/workspaces/platform/docs/adr/',
    path: '/workspaces/platform/docs/adr/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesPlatformComponentsUiIndexRoute =
  AdminWorkspacesPlatformComponentsUiIndexRouteImport.update({
    id: '/workspaces/platform/components/ui/',
    path: '/workspaces/platform/components/ui/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesPlatformComponentsNavigationIndexRoute =
  AdminWorkspacesPlatformComponentsNavigationIndexRouteImport.update({
    id: '/workspaces/platform/components/navigation/',
    path: '/workspaces/platform/components/navigation/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWorkspacesPlatformComponentsMarketingIndexRoute =
  AdminWorkspacesPlatformComponentsMarketingIndexRouteImport.update({
    id: '/workspaces/platform/components/marketing/',
    path: '/workspaces/platform/components/marketing/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/account/notifications': typeof AuthAccountNotificationsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/admin/kb/$slug': typeof AdminKbSlugRoute
  '/admin/media/$assetId': typeof AdminMediaAssetIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/': typeof AuthAccountIndexRoute
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/privacy-policy/': typeof LegalPrivacyPolicyIndexRoute
  '/about/': typeof PublicAboutIndexRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/contact/': typeof PublicContactIndexRoute
  '/portfolio/': typeof PublicPortfolioIndexRoute
  '/services/': typeof PublicServicesIndexRoute
  '/unsubscribe/': typeof PublicUnsubscribeIndexRoute
  '/admin/account/': typeof AdminAccountIndexRoute
  '/admin/components/': typeof AdminComponentsIndexRoute
  '/admin/contacts/': typeof AdminContactsIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/docs/': typeof AdminDocsIndexRoute
  '/admin/email/': typeof AdminEmailIndexRoute
  '/admin/kb/': typeof AdminKbIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
  '/admin/content/posts/$id': typeof AdminContentPostsIdRoute
  '/admin/content/posts/new': typeof AdminContentPostsNewRoute
  '/api/email/webhooks/resend': typeof ApiEmailWebhooksResendRoute
  '/admin/components/marketing/': typeof AdminComponentsMarketingIndexRoute
  '/admin/components/navigation/': typeof AdminComponentsNavigationIndexRoute
  '/admin/components/ui/': typeof AdminComponentsUiIndexRoute
  '/admin/content/posts/': typeof AdminContentPostsIndexRoute
  '/admin/docs/adr/': typeof AdminDocsAdrIndexRoute
  '/admin/docs/architecture/': typeof AdminDocsArchitectureIndexRoute
  '/admin/docs/phases/': typeof AdminDocsPhasesIndexRoute
  '/admin/workspaces/content/': typeof AdminWorkspacesContentIndexRoute
  '/admin/workspaces/operations/': typeof AdminWorkspacesOperationsIndexRoute
  '/admin/workspaces/platform/': typeof AdminWorkspacesPlatformIndexRoute
  '/admin/workspaces/content/kb/$slug': typeof AdminWorkspacesContentKbSlugRoute
  '/admin/workspaces/content/media/$assetId': typeof AdminWorkspacesContentMediaAssetIdRoute
  '/admin/workspaces/content/posts/$id': typeof AdminWorkspacesContentPostsIdRoute
  '/admin/workspaces/content/posts/new': typeof AdminWorkspacesContentPostsNewRoute
  '/admin/workspaces/operations/users/$userId': typeof AdminWorkspacesOperationsUsersUserIdRoute
  '/admin/workspaces/content/kb/': typeof AdminWorkspacesContentKbIndexRoute
  '/admin/workspaces/content/media/': typeof AdminWorkspacesContentMediaIndexRoute
  '/admin/workspaces/content/posts/': typeof AdminWorkspacesContentPostsIndexRoute
  '/admin/workspaces/operations/account/': typeof AdminWorkspacesOperationsAccountIndexRoute
  '/admin/workspaces/operations/contacts/': typeof AdminWorkspacesOperationsContactsIndexRoute
  '/admin/workspaces/operations/dashboard/': typeof AdminWorkspacesOperationsDashboardIndexRoute
  '/admin/workspaces/operations/email/': typeof AdminWorkspacesOperationsEmailIndexRoute
  '/admin/workspaces/operations/settings/': typeof AdminWorkspacesOperationsSettingsIndexRoute
  '/admin/workspaces/operations/users/': typeof AdminWorkspacesOperationsUsersIndexRoute
  '/admin/workspaces/platform/components/': typeof AdminWorkspacesPlatformComponentsIndexRoute
  '/admin/workspaces/platform/docs/': typeof AdminWorkspacesPlatformDocsIndexRoute
  '/admin/workspaces/platform/components/marketing/': typeof AdminWorkspacesPlatformComponentsMarketingIndexRoute
  '/admin/workspaces/platform/components/navigation/': typeof AdminWorkspacesPlatformComponentsNavigationIndexRoute
  '/admin/workspaces/platform/components/ui/': typeof AdminWorkspacesPlatformComponentsUiIndexRoute
  '/admin/workspaces/platform/docs/adr/': typeof AdminWorkspacesPlatformDocsAdrIndexRoute
  '/admin/workspaces/platform/docs/architecture/': typeof AdminWorkspacesPlatformDocsArchitectureIndexRoute
  '/admin/workspaces/platform/docs/phases/': typeof AdminWorkspacesPlatformDocsPhasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/notifications': typeof AuthAccountNotificationsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/admin/kb/$slug': typeof AdminKbSlugRoute
  '/admin/media/$assetId': typeof AdminMediaAssetIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account': typeof AuthAccountIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/privacy-policy': typeof LegalPrivacyPolicyIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/contact': typeof PublicContactIndexRoute
  '/portfolio': typeof PublicPortfolioIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/unsubscribe': typeof PublicUnsubscribeIndexRoute
  '/admin/account': typeof AdminAccountIndexRoute
  '/admin/components': typeof AdminComponentsIndexRoute
  '/admin/contacts': typeof AdminContactsIndexRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/docs': typeof AdminDocsIndexRoute
  '/admin/email': typeof AdminEmailIndexRoute
  '/admin/kb': typeof AdminKbIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/workspaces': typeof AdminWorkspacesIndexRoute
  '/admin/content/posts/$id': typeof AdminContentPostsIdRoute
  '/admin/content/posts/new': typeof AdminContentPostsNewRoute
  '/api/email/webhooks/resend': typeof ApiEmailWebhooksResendRoute
  '/admin/components/marketing': typeof AdminComponentsMarketingIndexRoute
  '/admin/components/navigation': typeof AdminComponentsNavigationIndexRoute
  '/admin/components/ui': typeof AdminComponentsUiIndexRoute
  '/admin/content/posts': typeof AdminContentPostsIndexRoute
  '/admin/docs/adr': typeof AdminDocsAdrIndexRoute
  '/admin/docs/architecture': typeof AdminDocsArchitectureIndexRoute
  '/admin/docs/phases': typeof AdminDocsPhasesIndexRoute
  '/admin/workspaces/content': typeof AdminWorkspacesContentIndexRoute
  '/admin/workspaces/operations': typeof AdminWorkspacesOperationsIndexRoute
  '/admin/workspaces/platform': typeof AdminWorkspacesPlatformIndexRoute
  '/admin/workspaces/content/kb/$slug': typeof AdminWorkspacesContentKbSlugRoute
  '/admin/workspaces/content/media/$assetId': typeof AdminWorkspacesContentMediaAssetIdRoute
  '/admin/workspaces/content/posts/$id': typeof AdminWorkspacesContentPostsIdRoute
  '/admin/workspaces/content/posts/new': typeof AdminWorkspacesContentPostsNewRoute
  '/admin/workspaces/operations/users/$userId': typeof AdminWorkspacesOperationsUsersUserIdRoute
  '/admin/workspaces/content/kb': typeof AdminWorkspacesContentKbIndexRoute
  '/admin/workspaces/content/media': typeof AdminWorkspacesContentMediaIndexRoute
  '/admin/workspaces/content/posts': typeof AdminWorkspacesContentPostsIndexRoute
  '/admin/workspaces/operations/account': typeof AdminWorkspacesOperationsAccountIndexRoute
  '/admin/workspaces/operations/contacts': typeof AdminWorkspacesOperationsContactsIndexRoute
  '/admin/workspaces/operations/dashboard': typeof AdminWorkspacesOperationsDashboardIndexRoute
  '/admin/workspaces/operations/email': typeof AdminWorkspacesOperationsEmailIndexRoute
  '/admin/workspaces/operations/settings': typeof AdminWorkspacesOperationsSettingsIndexRoute
  '/admin/workspaces/operations/users': typeof AdminWorkspacesOperationsUsersIndexRoute
  '/admin/workspaces/platform/components': typeof AdminWorkspacesPlatformComponentsIndexRoute
  '/admin/workspaces/platform/docs': typeof AdminWorkspacesPlatformDocsIndexRoute
  '/admin/workspaces/platform/components/marketing': typeof AdminWorkspacesPlatformComponentsMarketingIndexRoute
  '/admin/workspaces/platform/components/navigation': typeof AdminWorkspacesPlatformComponentsNavigationIndexRoute
  '/admin/workspaces/platform/components/ui': typeof AdminWorkspacesPlatformComponentsUiIndexRoute
  '/admin/workspaces/platform/docs/adr': typeof AdminWorkspacesPlatformDocsAdrIndexRoute
  '/admin/workspaces/platform/docs/architecture': typeof AdminWorkspacesPlatformDocsArchitectureIndexRoute
  '/admin/workspaces/platform/docs/phases': typeof AdminWorkspacesPlatformDocsPhasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_legal': typeof LegalRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_auth/account/notifications': typeof AuthAccountNotificationsRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/admin/kb/$slug': typeof AdminKbSlugRoute
  '/admin/media/$assetId': typeof AdminMediaAssetIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/account/': typeof AuthAccountIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/_legal/privacy-policy/': typeof LegalPrivacyPolicyIndexRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/contact/': typeof PublicContactIndexRoute
  '/_public/portfolio/': typeof PublicPortfolioIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
  '/_public/unsubscribe/': typeof PublicUnsubscribeIndexRoute
  '/admin/account/': typeof AdminAccountIndexRoute
  '/admin/components/': typeof AdminComponentsIndexRoute
  '/admin/contacts/': typeof AdminContactsIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/docs/': typeof AdminDocsIndexRoute
  '/admin/email/': typeof AdminEmailIndexRoute
  '/admin/kb/': typeof AdminKbIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
  '/admin/content/posts/$id': typeof AdminContentPostsIdRoute
  '/admin/content/posts/new': typeof AdminContentPostsNewRoute
  '/api/email/webhooks/resend': typeof ApiEmailWebhooksResendRoute
  '/admin/components/marketing/': typeof AdminComponentsMarketingIndexRoute
  '/admin/components/navigation/': typeof AdminComponentsNavigationIndexRoute
  '/admin/components/ui/': typeof AdminComponentsUiIndexRoute
  '/admin/content/posts/': typeof AdminContentPostsIndexRoute
  '/admin/docs/adr/': typeof AdminDocsAdrIndexRoute
  '/admin/docs/architecture/': typeof AdminDocsArchitectureIndexRoute
  '/admin/docs/phases/': typeof AdminDocsPhasesIndexRoute
  '/admin/workspaces/content/': typeof AdminWorkspacesContentIndexRoute
  '/admin/workspaces/operations/': typeof AdminWorkspacesOperationsIndexRoute
  '/admin/workspaces/platform/': typeof AdminWorkspacesPlatformIndexRoute
  '/admin/workspaces/content/kb/$slug': typeof AdminWorkspacesContentKbSlugRoute
  '/admin/workspaces/content/media/$assetId': typeof AdminWorkspacesContentMediaAssetIdRoute
  '/admin/workspaces/content/posts/$id': typeof AdminWorkspacesContentPostsIdRoute
  '/admin/workspaces/content/posts/new': typeof AdminWorkspacesContentPostsNewRoute
  '/admin/workspaces/operations/users/$userId': typeof AdminWorkspacesOperationsUsersUserIdRoute
  '/admin/workspaces/content/kb/': typeof AdminWorkspacesContentKbIndexRoute
  '/admin/workspaces/content/media/': typeof AdminWorkspacesContentMediaIndexRoute
  '/admin/workspaces/content/posts/': typeof AdminWorkspacesContentPostsIndexRoute
  '/admin/workspaces/operations/account/': typeof AdminWorkspacesOperationsAccountIndexRoute
  '/admin/workspaces/operations/contacts/': typeof AdminWorkspacesOperationsContactsIndexRoute
  '/admin/workspaces/operations/dashboard/': typeof AdminWorkspacesOperationsDashboardIndexRoute
  '/admin/workspaces/operations/email/': typeof AdminWorkspacesOperationsEmailIndexRoute
  '/admin/workspaces/operations/settings/': typeof AdminWorkspacesOperationsSettingsIndexRoute
  '/admin/workspaces/operations/users/': typeof AdminWorkspacesOperationsUsersIndexRoute
  '/admin/workspaces/platform/components/': typeof AdminWorkspacesPlatformComponentsIndexRoute
  '/admin/workspaces/platform/docs/': typeof AdminWorkspacesPlatformDocsIndexRoute
  '/admin/workspaces/platform/components/marketing/': typeof AdminWorkspacesPlatformComponentsMarketingIndexRoute
  '/admin/workspaces/platform/components/navigation/': typeof AdminWorkspacesPlatformComponentsNavigationIndexRoute
  '/admin/workspaces/platform/components/ui/': typeof AdminWorkspacesPlatformComponentsUiIndexRoute
  '/admin/workspaces/platform/docs/adr/': typeof AdminWorkspacesPlatformDocsAdrIndexRoute
  '/admin/workspaces/platform/docs/architecture/': typeof AdminWorkspacesPlatformDocsArchitectureIndexRoute
  '/admin/workspaces/platform/docs/phases/': typeof AdminWorkspacesPlatformDocsPhasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/'
    | '/account/notifications'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/admin/kb/$slug'
    | '/admin/media/$assetId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/account/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/signup/'
    | '/privacy-policy/'
    | '/about/'
    | '/blog/'
    | '/contact/'
    | '/portfolio/'
    | '/services/'
    | '/unsubscribe/'
    | '/admin/account/'
    | '/admin/components/'
    | '/admin/contacts/'
    | '/admin/content/'
    | '/admin/dashboard/'
    | '/admin/docs/'
    | '/admin/email/'
    | '/admin/kb/'
    | '/admin/media/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/workspaces/'
    | '/admin/content/posts/$id'
    | '/admin/content/posts/new'
    | '/api/email/webhooks/resend'
    | '/admin/components/marketing/'
    | '/admin/components/navigation/'
    | '/admin/components/ui/'
    | '/admin/content/posts/'
    | '/admin/docs/adr/'
    | '/admin/docs/architecture/'
    | '/admin/docs/phases/'
    | '/admin/workspaces/content/'
    | '/admin/workspaces/operations/'
    | '/admin/workspaces/platform/'
    | '/admin/workspaces/content/kb/$slug'
    | '/admin/workspaces/content/media/$assetId'
    | '/admin/workspaces/content/posts/$id'
    | '/admin/workspaces/content/posts/new'
    | '/admin/workspaces/operations/users/$userId'
    | '/admin/workspaces/content/kb/'
    | '/admin/workspaces/content/media/'
    | '/admin/workspaces/content/posts/'
    | '/admin/workspaces/operations/account/'
    | '/admin/workspaces/operations/contacts/'
    | '/admin/workspaces/operations/dashboard/'
    | '/admin/workspaces/operations/email/'
    | '/admin/workspaces/operations/settings/'
    | '/admin/workspaces/operations/users/'
    | '/admin/workspaces/platform/components/'
    | '/admin/workspaces/platform/docs/'
    | '/admin/workspaces/platform/components/marketing/'
    | '/admin/workspaces/platform/components/navigation/'
    | '/admin/workspaces/platform/components/ui/'
    | '/admin/workspaces/platform/docs/adr/'
    | '/admin/workspaces/platform/docs/architecture/'
    | '/admin/workspaces/platform/docs/phases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/account/notifications'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/admin/kb/$slug'
    | '/admin/media/$assetId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/privacy-policy'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/unsubscribe'
    | '/admin/account'
    | '/admin/components'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/docs'
    | '/admin/email'
    | '/admin/kb'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/workspaces'
    | '/admin/content/posts/$id'
    | '/admin/content/posts/new'
    | '/api/email/webhooks/resend'
    | '/admin/components/marketing'
    | '/admin/components/navigation'
    | '/admin/components/ui'
    | '/admin/content/posts'
    | '/admin/docs/adr'
    | '/admin/docs/architecture'
    | '/admin/docs/phases'
    | '/admin/workspaces/content'
    | '/admin/workspaces/operations'
    | '/admin/workspaces/platform'
    | '/admin/workspaces/content/kb/$slug'
    | '/admin/workspaces/content/media/$assetId'
    | '/admin/workspaces/content/posts/$id'
    | '/admin/workspaces/content/posts/new'
    | '/admin/workspaces/operations/users/$userId'
    | '/admin/workspaces/content/kb'
    | '/admin/workspaces/content/media'
    | '/admin/workspaces/content/posts'
    | '/admin/workspaces/operations/account'
    | '/admin/workspaces/operations/contacts'
    | '/admin/workspaces/operations/dashboard'
    | '/admin/workspaces/operations/email'
    | '/admin/workspaces/operations/settings'
    | '/admin/workspaces/operations/users'
    | '/admin/workspaces/platform/components'
    | '/admin/workspaces/platform/docs'
    | '/admin/workspaces/platform/components/marketing'
    | '/admin/workspaces/platform/components/navigation'
    | '/admin/workspaces/platform/components/ui'
    | '/admin/workspaces/platform/docs/adr'
    | '/admin/workspaces/platform/docs/architecture'
    | '/admin/workspaces/platform/docs/phases'
  id:
    | '__root__'
    | '/_auth'
    | '/_legal'
    | '/_public'
    | '/admin'
    | '/_public/'
    | '/admin/'
    | '/_auth/account/notifications'
    | '/_public/blog/$slug'
    | '/_public/portfolio/$slug'
    | '/admin/kb/$slug'
    | '/admin/media/$assetId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/_auth/account/'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/reset-password/'
    | '/_auth/signup/'
    | '/_legal/privacy-policy/'
    | '/_public/about/'
    | '/_public/blog/'
    | '/_public/contact/'
    | '/_public/portfolio/'
    | '/_public/services/'
    | '/_public/unsubscribe/'
    | '/admin/account/'
    | '/admin/components/'
    | '/admin/contacts/'
    | '/admin/content/'
    | '/admin/dashboard/'
    | '/admin/docs/'
    | '/admin/email/'
    | '/admin/kb/'
    | '/admin/media/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/workspaces/'
    | '/admin/content/posts/$id'
    | '/admin/content/posts/new'
    | '/api/email/webhooks/resend'
    | '/admin/components/marketing/'
    | '/admin/components/navigation/'
    | '/admin/components/ui/'
    | '/admin/content/posts/'
    | '/admin/docs/adr/'
    | '/admin/docs/architecture/'
    | '/admin/docs/phases/'
    | '/admin/workspaces/content/'
    | '/admin/workspaces/operations/'
    | '/admin/workspaces/platform/'
    | '/admin/workspaces/content/kb/$slug'
    | '/admin/workspaces/content/media/$assetId'
    | '/admin/workspaces/content/posts/$id'
    | '/admin/workspaces/content/posts/new'
    | '/admin/workspaces/operations/users/$userId'
    | '/admin/workspaces/content/kb/'
    | '/admin/workspaces/content/media/'
    | '/admin/workspaces/content/posts/'
    | '/admin/workspaces/operations/account/'
    | '/admin/workspaces/operations/contacts/'
    | '/admin/workspaces/operations/dashboard/'
    | '/admin/workspaces/operations/email/'
    | '/admin/workspaces/operations/settings/'
    | '/admin/workspaces/operations/users/'
    | '/admin/workspaces/platform/components/'
    | '/admin/workspaces/platform/docs/'
    | '/admin/workspaces/platform/components/marketing/'
    | '/admin/workspaces/platform/components/navigation/'
    | '/admin/workspaces/platform/components/ui/'
    | '/admin/workspaces/platform/docs/adr/'
    | '/admin/workspaces/platform/docs/architecture/'
    | '/admin/workspaces/platform/docs/phases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEmailWebhooksResendRoute: typeof ApiEmailWebhooksResendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/workspaces/': {
      id: '/admin/workspaces/'
      path: '/workspaces'
      fullPath: '/admin/workspaces/'
      preLoaderRoute: typeof AdminWorkspacesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kb/': {
      id: '/admin/kb/'
      path: '/kb'
      fullPath: '/admin/kb/'
      preLoaderRoute: typeof AdminKbIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/': {
      id: '/admin/email/'
      path: '/email'
      fullPath: '/admin/email/'
      preLoaderRoute: typeof AdminEmailIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/docs/': {
      id: '/admin/docs/'
      path: '/docs'
      fullPath: '/admin/docs/'
      preLoaderRoute: typeof AdminDocsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contacts/': {
      id: '/admin/contacts/'
      path: '/contacts'
      fullPath: '/admin/contacts/'
      preLoaderRoute: typeof AdminContactsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/components/': {
      id: '/admin/components/'
      path: '/components'
      fullPath: '/admin/components/'
      preLoaderRoute: typeof AdminComponentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/account/': {
      id: '/admin/account/'
      path: '/account'
      fullPath: '/admin/account/'
      preLoaderRoute: typeof AdminAccountIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/unsubscribe/': {
      id: '/_public/unsubscribe/'
      path: '/unsubscribe'
      fullPath: '/unsubscribe/'
      preLoaderRoute: typeof PublicUnsubscribeIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/portfolio/': {
      id: '/_public/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PublicPortfolioIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact/': {
      id: '/_public/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof PublicContactIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PublicAboutIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_legal/privacy-policy/': {
      id: '/_legal/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof LegalPrivacyPolicyIndexRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/': {
      id: '/_auth/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthAccountIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/$assetId': {
      id: '/admin/media/$assetId'
      path: '/media/$assetId'
      fullPath: '/admin/media/$assetId'
      preLoaderRoute: typeof AdminMediaAssetIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kb/$slug': {
      id: '/admin/kb/$slug'
      path: '/kb/$slug'
      fullPath: '/admin/kb/$slug'
      preLoaderRoute: typeof AdminKbSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/portfolio/$slug': {
      id: '/_public/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PublicPortfolioSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/account/notifications': {
      id: '/_auth/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthAccountNotificationsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/workspaces/platform/': {
      id: '/admin/workspaces/platform/'
      path: '/workspaces/platform'
      fullPath: '/admin/workspaces/platform/'
      preLoaderRoute: typeof AdminWorkspacesPlatformIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/operations/': {
      id: '/admin/workspaces/operations/'
      path: '/workspaces/operations'
      fullPath: '/admin/workspaces/operations/'
      preLoaderRoute: typeof AdminWorkspacesOperationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/content/': {
      id: '/admin/workspaces/content/'
      path: '/workspaces/content'
      fullPath: '/admin/workspaces/content/'
      preLoaderRoute: typeof AdminWorkspacesContentIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/docs/phases/': {
      id: '/admin/docs/phases/'
      path: '/docs/phases'
      fullPath: '/admin/docs/phases/'
      preLoaderRoute: typeof AdminDocsPhasesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/docs/architecture/': {
      id: '/admin/docs/architecture/'
      path: '/docs/architecture'
      fullPath: '/admin/docs/architecture/'
      preLoaderRoute: typeof AdminDocsArchitectureIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/docs/adr/': {
      id: '/admin/docs/adr/'
      path: '/docs/adr'
      fullPath: '/admin/docs/adr/'
      preLoaderRoute: typeof AdminDocsAdrIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/posts/': {
      id: '/admin/content/posts/'
      path: '/content/posts'
      fullPath: '/admin/content/posts/'
      preLoaderRoute: typeof AdminContentPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/components/ui/': {
      id: '/admin/components/ui/'
      path: '/components/ui'
      fullPath: '/admin/components/ui/'
      preLoaderRoute: typeof AdminComponentsUiIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/components/navigation/': {
      id: '/admin/components/navigation/'
      path: '/components/navigation'
      fullPath: '/admin/components/navigation/'
      preLoaderRoute: typeof AdminComponentsNavigationIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/components/marketing/': {
      id: '/admin/components/marketing/'
      path: '/components/marketing'
      fullPath: '/admin/components/marketing/'
      preLoaderRoute: typeof AdminComponentsMarketingIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/email/webhooks/resend': {
      id: '/api/email/webhooks/resend'
      path: '/api/email/webhooks/resend'
      fullPath: '/api/email/webhooks/resend'
      preLoaderRoute: typeof ApiEmailWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/posts/new': {
      id: '/admin/content/posts/new'
      path: '/content/posts/new'
      fullPath: '/admin/content/posts/new'
      preLoaderRoute: typeof AdminContentPostsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/posts/$id': {
      id: '/admin/content/posts/$id'
      path: '/content/posts/$id'
      fullPath: '/admin/content/posts/$id'
      preLoaderRoute: typeof AdminContentPostsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/platform/docs/': {
      id: '/admin/workspaces/platform/docs/'
      path: '/workspaces/platform/docs'
      fullPath: '/admin/workspaces/platform/docs/'
      preLoaderRoute: typeof AdminWorkspacesPlatformDocsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/platform/components/': {
      id: '/admin/workspaces/platform/components/'
      path: '/workspaces/platform/components'
      fullPath: '/admin/workspaces/platform/components/'
      preLoaderRoute: typeof AdminWorkspacesPlatformComponentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/operations/users/': {
      id: '/admin/workspaces/operations/users/'
      path: '/workspaces/operations/users'
      fullPath: '/admin/workspaces/operations/users/'
      preLoaderRoute: typeof AdminWorkspacesOperationsUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/operations/settings/': {
      id: '/admin/workspaces/operations/settings/'
      path: '/workspaces/operations/settings'
      fullPath: '/admin/workspaces/operations/settings/'
      preLoaderRoute: typeof AdminWorkspacesOperationsSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/operations/email/': {
      id: '/admin/workspaces/operations/email/'
      path: '/workspaces/operations/email'
      fullPath: '/admin/workspaces/operations/email/'
      preLoaderRoute: typeof AdminWorkspacesOperationsEmailIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/operations/dashboard/': {
      id: '/admin/workspaces/operations/dashboard/'
      path: '/workspaces/operations/dashboard'
      fullPath: '/admin/workspaces/operations/dashboard/'
      preLoaderRoute: typeof AdminWorkspacesOperationsDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/operations/contacts/': {
      id: '/admin/workspaces/operations/contacts/'
      path: '/workspaces/operations/contacts'
      fullPath: '/admin/workspaces/operations/contacts/'
      preLoaderRoute: typeof AdminWorkspacesOperationsContactsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/operations/account/': {
      id: '/admin/workspaces/operations/account/'
      path: '/workspaces/operations/account'
      fullPath: '/admin/workspaces/operations/account/'
      preLoaderRoute: typeof AdminWorkspacesOperationsAccountIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/content/posts/': {
      id: '/admin/workspaces/content/posts/'
      path: '/workspaces/content/posts'
      fullPath: '/admin/workspaces/content/posts/'
      preLoaderRoute: typeof AdminWorkspacesContentPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/content/media/': {
      id: '/admin/workspaces/content/media/'
      path: '/workspaces/content/media'
      fullPath: '/admin/workspaces/content/media/'
      preLoaderRoute: typeof AdminWorkspacesContentMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/content/kb/': {
      id: '/admin/workspaces/content/kb/'
      path: '/workspaces/content/kb'
      fullPath: '/admin/workspaces/content/kb/'
      preLoaderRoute: typeof AdminWorkspacesContentKbIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/operations/users/$userId': {
      id: '/admin/workspaces/operations/users/$userId'
      path: '/workspaces/operations/users/$userId'
      fullPath: '/admin/workspaces/operations/users/$userId'
      preLoaderRoute: typeof AdminWorkspacesOperationsUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/content/posts/new': {
      id: '/admin/workspaces/content/posts/new'
      path: '/workspaces/content/posts/new'
      fullPath: '/admin/workspaces/content/posts/new'
      preLoaderRoute: typeof AdminWorkspacesContentPostsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/content/posts/$id': {
      id: '/admin/workspaces/content/posts/$id'
      path: '/workspaces/content/posts/$id'
      fullPath: '/admin/workspaces/content/posts/$id'
      preLoaderRoute: typeof AdminWorkspacesContentPostsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/content/media/$assetId': {
      id: '/admin/workspaces/content/media/$assetId'
      path: '/workspaces/content/media/$assetId'
      fullPath: '/admin/workspaces/content/media/$assetId'
      preLoaderRoute: typeof AdminWorkspacesContentMediaAssetIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/content/kb/$slug': {
      id: '/admin/workspaces/content/kb/$slug'
      path: '/workspaces/content/kb/$slug'
      fullPath: '/admin/workspaces/content/kb/$slug'
      preLoaderRoute: typeof AdminWorkspacesContentKbSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/platform/docs/phases/': {
      id: '/admin/workspaces/platform/docs/phases/'
      path: '/workspaces/platform/docs/phases'
      fullPath: '/admin/workspaces/platform/docs/phases/'
      preLoaderRoute: typeof AdminWorkspacesPlatformDocsPhasesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/platform/docs/architecture/': {
      id: '/admin/workspaces/platform/docs/architecture/'
      path: '/workspaces/platform/docs/architecture'
      fullPath: '/admin/workspaces/platform/docs/architecture/'
      preLoaderRoute: typeof AdminWorkspacesPlatformDocsArchitectureIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/platform/docs/adr/': {
      id: '/admin/workspaces/platform/docs/adr/'
      path: '/workspaces/platform/docs/adr'
      fullPath: '/admin/workspaces/platform/docs/adr/'
      preLoaderRoute: typeof AdminWorkspacesPlatformDocsAdrIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/platform/components/ui/': {
      id: '/admin/workspaces/platform/components/ui/'
      path: '/workspaces/platform/components/ui'
      fullPath: '/admin/workspaces/platform/components/ui/'
      preLoaderRoute: typeof AdminWorkspacesPlatformComponentsUiIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/platform/components/navigation/': {
      id: '/admin/workspaces/platform/components/navigation/'
      path: '/workspaces/platform/components/navigation'
      fullPath: '/admin/workspaces/platform/components/navigation/'
      preLoaderRoute: typeof AdminWorkspacesPlatformComponentsNavigationIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workspaces/platform/components/marketing/': {
      id: '/admin/workspaces/platform/components/marketing/'
      path: '/workspaces/platform/components/marketing'
      fullPath: '/admin/workspaces/platform/components/marketing/'
      preLoaderRoute: typeof AdminWorkspacesPlatformComponentsMarketingIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAccountNotificationsRoute: typeof AuthAccountNotificationsRoute
  AuthAccountIndexRoute: typeof AuthAccountIndexRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAccountNotificationsRoute: AuthAccountNotificationsRoute,
  AuthAccountIndexRoute: AuthAccountIndexRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface LegalRouteRouteChildren {
  LegalPrivacyPolicyIndexRoute: typeof LegalPrivacyPolicyIndexRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalPrivacyPolicyIndexRoute: LegalPrivacyPolicyIndexRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicPortfolioSlugRoute: typeof PublicPortfolioSlugRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicContactIndexRoute: typeof PublicContactIndexRoute
  PublicPortfolioIndexRoute: typeof PublicPortfolioIndexRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
  PublicUnsubscribeIndexRoute: typeof PublicUnsubscribeIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicPortfolioSlugRoute: PublicPortfolioSlugRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicContactIndexRoute: PublicContactIndexRoute,
  PublicPortfolioIndexRoute: PublicPortfolioIndexRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
  PublicUnsubscribeIndexRoute: PublicUnsubscribeIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminKbSlugRoute: typeof AdminKbSlugRoute
  AdminMediaAssetIdRoute: typeof AdminMediaAssetIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminAccountIndexRoute: typeof AdminAccountIndexRoute
  AdminComponentsIndexRoute: typeof AdminComponentsIndexRoute
  AdminContactsIndexRoute: typeof AdminContactsIndexRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDocsIndexRoute: typeof AdminDocsIndexRoute
  AdminEmailIndexRoute: typeof AdminEmailIndexRoute
  AdminKbIndexRoute: typeof AdminKbIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminWorkspacesIndexRoute: typeof AdminWorkspacesIndexRoute
  AdminContentPostsIdRoute: typeof AdminContentPostsIdRoute
  AdminContentPostsNewRoute: typeof AdminContentPostsNewRoute
  AdminComponentsMarketingIndexRoute: typeof AdminComponentsMarketingIndexRoute
  AdminComponentsNavigationIndexRoute: typeof AdminComponentsNavigationIndexRoute
  AdminComponentsUiIndexRoute: typeof AdminComponentsUiIndexRoute
  AdminContentPostsIndexRoute: typeof AdminContentPostsIndexRoute
  AdminDocsAdrIndexRoute: typeof AdminDocsAdrIndexRoute
  AdminDocsArchitectureIndexRoute: typeof AdminDocsArchitectureIndexRoute
  AdminDocsPhasesIndexRoute: typeof AdminDocsPhasesIndexRoute
  AdminWorkspacesContentIndexRoute: typeof AdminWorkspacesContentIndexRoute
  AdminWorkspacesOperationsIndexRoute: typeof AdminWorkspacesOperationsIndexRoute
  AdminWorkspacesPlatformIndexRoute: typeof AdminWorkspacesPlatformIndexRoute
  AdminWorkspacesContentKbSlugRoute: typeof AdminWorkspacesContentKbSlugRoute
  AdminWorkspacesContentMediaAssetIdRoute: typeof AdminWorkspacesContentMediaAssetIdRoute
  AdminWorkspacesContentPostsIdRoute: typeof AdminWorkspacesContentPostsIdRoute
  AdminWorkspacesContentPostsNewRoute: typeof AdminWorkspacesContentPostsNewRoute
  AdminWorkspacesOperationsUsersUserIdRoute: typeof AdminWorkspacesOperationsUsersUserIdRoute
  AdminWorkspacesContentKbIndexRoute: typeof AdminWorkspacesContentKbIndexRoute
  AdminWorkspacesContentMediaIndexRoute: typeof AdminWorkspacesContentMediaIndexRoute
  AdminWorkspacesContentPostsIndexRoute: typeof AdminWorkspacesContentPostsIndexRoute
  AdminWorkspacesOperationsAccountIndexRoute: typeof AdminWorkspacesOperationsAccountIndexRoute
  AdminWorkspacesOperationsContactsIndexRoute: typeof AdminWorkspacesOperationsContactsIndexRoute
  AdminWorkspacesOperationsDashboardIndexRoute: typeof AdminWorkspacesOperationsDashboardIndexRoute
  AdminWorkspacesOperationsEmailIndexRoute: typeof AdminWorkspacesOperationsEmailIndexRoute
  AdminWorkspacesOperationsSettingsIndexRoute: typeof AdminWorkspacesOperationsSettingsIndexRoute
  AdminWorkspacesOperationsUsersIndexRoute: typeof AdminWorkspacesOperationsUsersIndexRoute
  AdminWorkspacesPlatformComponentsIndexRoute: typeof AdminWorkspacesPlatformComponentsIndexRoute
  AdminWorkspacesPlatformDocsIndexRoute: typeof AdminWorkspacesPlatformDocsIndexRoute
  AdminWorkspacesPlatformComponentsMarketingIndexRoute: typeof AdminWorkspacesPlatformComponentsMarketingIndexRoute
  AdminWorkspacesPlatformComponentsNavigationIndexRoute: typeof AdminWorkspacesPlatformComponentsNavigationIndexRoute
  AdminWorkspacesPlatformComponentsUiIndexRoute: typeof AdminWorkspacesPlatformComponentsUiIndexRoute
  AdminWorkspacesPlatformDocsAdrIndexRoute: typeof AdminWorkspacesPlatformDocsAdrIndexRoute
  AdminWorkspacesPlatformDocsArchitectureIndexRoute: typeof AdminWorkspacesPlatformDocsArchitectureIndexRoute
  AdminWorkspacesPlatformDocsPhasesIndexRoute: typeof AdminWorkspacesPlatformDocsPhasesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminKbSlugRoute: AdminKbSlugRoute,
  AdminMediaAssetIdRoute: AdminMediaAssetIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminAccountIndexRoute: AdminAccountIndexRoute,
  AdminComponentsIndexRoute: AdminComponentsIndexRoute,
  AdminContactsIndexRoute: AdminContactsIndexRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDocsIndexRoute: AdminDocsIndexRoute,
  AdminEmailIndexRoute: AdminEmailIndexRoute,
  AdminKbIndexRoute: AdminKbIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminWorkspacesIndexRoute: AdminWorkspacesIndexRoute,
  AdminContentPostsIdRoute: AdminContentPostsIdRoute,
  AdminContentPostsNewRoute: AdminContentPostsNewRoute,
  AdminComponentsMarketingIndexRoute: AdminComponentsMarketingIndexRoute,
  AdminComponentsNavigationIndexRoute: AdminComponentsNavigationIndexRoute,
  AdminComponentsUiIndexRoute: AdminComponentsUiIndexRoute,
  AdminContentPostsIndexRoute: AdminContentPostsIndexRoute,
  AdminDocsAdrIndexRoute: AdminDocsAdrIndexRoute,
  AdminDocsArchitectureIndexRoute: AdminDocsArchitectureIndexRoute,
  AdminDocsPhasesIndexRoute: AdminDocsPhasesIndexRoute,
  AdminWorkspacesContentIndexRoute: AdminWorkspacesContentIndexRoute,
  AdminWorkspacesOperationsIndexRoute: AdminWorkspacesOperationsIndexRoute,
  AdminWorkspacesPlatformIndexRoute: AdminWorkspacesPlatformIndexRoute,
  AdminWorkspacesContentKbSlugRoute: AdminWorkspacesContentKbSlugRoute,
  AdminWorkspacesContentMediaAssetIdRoute:
    AdminWorkspacesContentMediaAssetIdRoute,
  AdminWorkspacesContentPostsIdRoute: AdminWorkspacesContentPostsIdRoute,
  AdminWorkspacesContentPostsNewRoute: AdminWorkspacesContentPostsNewRoute,
  AdminWorkspacesOperationsUsersUserIdRoute:
    AdminWorkspacesOperationsUsersUserIdRoute,
  AdminWorkspacesContentKbIndexRoute: AdminWorkspacesContentKbIndexRoute,
  AdminWorkspacesContentMediaIndexRoute: AdminWorkspacesContentMediaIndexRoute,
  AdminWorkspacesContentPostsIndexRoute: AdminWorkspacesContentPostsIndexRoute,
  AdminWorkspacesOperationsAccountIndexRoute:
    AdminWorkspacesOperationsAccountIndexRoute,
  AdminWorkspacesOperationsContactsIndexRoute:
    AdminWorkspacesOperationsContactsIndexRoute,
  AdminWorkspacesOperationsDashboardIndexRoute:
    AdminWorkspacesOperationsDashboardIndexRoute,
  AdminWorkspacesOperationsEmailIndexRoute:
    AdminWorkspacesOperationsEmailIndexRoute,
  AdminWorkspacesOperationsSettingsIndexRoute:
    AdminWorkspacesOperationsSettingsIndexRoute,
  AdminWorkspacesOperationsUsersIndexRoute:
    AdminWorkspacesOperationsUsersIndexRoute,
  AdminWorkspacesPlatformComponentsIndexRoute:
    AdminWorkspacesPlatformComponentsIndexRoute,
  AdminWorkspacesPlatformDocsIndexRoute: AdminWorkspacesPlatformDocsIndexRoute,
  AdminWorkspacesPlatformComponentsMarketingIndexRoute:
    AdminWorkspacesPlatformComponentsMarketingIndexRoute,
  AdminWorkspacesPlatformComponentsNavigationIndexRoute:
    AdminWorkspacesPlatformComponentsNavigationIndexRoute,
  AdminWorkspacesPlatformComponentsUiIndexRoute:
    AdminWorkspacesPlatformComponentsUiIndexRoute,
  AdminWorkspacesPlatformDocsAdrIndexRoute:
    AdminWorkspacesPlatformDocsAdrIndexRoute,
  AdminWorkspacesPlatformDocsArchitectureIndexRoute:
    AdminWorkspacesPlatformDocsArchitectureIndexRoute,
  AdminWorkspacesPlatformDocsPhasesIndexRoute:
    AdminWorkspacesPlatformDocsPhasesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEmailWebhooksResendRoute: ApiEmailWebhooksResendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
