/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as LegalRouteRouteImport } from './routes/_legal/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminKbIndexRouteImport } from './routes/admin/kb/index'
import { Route as AdminDocsIndexRouteImport } from './routes/admin/docs/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminContentIndexRouteImport } from './routes/admin/content/index'
import { Route as AdminComponentsIndexRouteImport } from './routes/admin/components/index'
import { Route as PublicServicesIndexRouteImport } from './routes/_public/services/index'
import { Route as PublicPortfolioIndexRouteImport } from './routes/_public/portfolio/index'
import { Route as PublicContactIndexRouteImport } from './routes/_public/contact/index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as PublicAboutIndexRouteImport } from './routes/_public/about/index'
import { Route as LegalPrivacyPolicyIndexRouteImport } from './routes/_legal/privacy-policy/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminKbSlugRouteImport } from './routes/admin/kb/$slug'
import { Route as PublicPortfolioSlugRouteImport } from './routes/_public/portfolio/$slug'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog/$slug'
import { Route as AdminDocsPhasesIndexRouteImport } from './routes/admin/docs/phases/index'
import { Route as AdminDocsArchitectureIndexRouteImport } from './routes/admin/docs/architecture/index'
import { Route as AdminDocsAdrIndexRouteImport } from './routes/admin/docs/adr/index'
import { Route as AdminContentPostsIndexRouteImport } from './routes/admin/content/posts/index'
import { Route as AdminComponentsUiIndexRouteImport } from './routes/admin/components/ui/index'
import { Route as AdminComponentsNavigationIndexRouteImport } from './routes/admin/components/navigation/index'
import { Route as AdminComponentsMarketingIndexRouteImport } from './routes/admin/components/marketing/index'
import { Route as AdminContentPostsNewRouteImport } from './routes/admin/content/posts/new'
import { Route as AdminContentPostsIdRouteImport } from './routes/admin/content/posts/$id'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKbIndexRoute = AdminKbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocsIndexRoute = AdminDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComponentsIndexRoute = AdminComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPortfolioIndexRoute = PublicPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactIndexRoute = PublicContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutIndexRoute = PublicAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const LegalPrivacyPolicyIndexRoute = LegalPrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => LegalRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKbSlugRoute = AdminKbSlugRouteImport.update({
  id: '/kb/$slug',
  path: '/kb/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicPortfolioSlugRoute = PublicPortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminDocsPhasesIndexRoute = AdminDocsPhasesIndexRouteImport.update({
  id: '/docs/phases/',
  path: '/docs/phases/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocsArchitectureIndexRoute =
  AdminDocsArchitectureIndexRouteImport.update({
    id: '/docs/architecture/',
    path: '/docs/architecture/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDocsAdrIndexRoute = AdminDocsAdrIndexRouteImport.update({
  id: '/docs/adr/',
  path: '/docs/adr/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentPostsIndexRoute = AdminContentPostsIndexRouteImport.update({
  id: '/content/posts/',
  path: '/content/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComponentsUiIndexRoute = AdminComponentsUiIndexRouteImport.update({
  id: '/components/ui/',
  path: '/components/ui/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComponentsNavigationIndexRoute =
  AdminComponentsNavigationIndexRouteImport.update({
    id: '/components/navigation/',
    path: '/components/navigation/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminComponentsMarketingIndexRoute =
  AdminComponentsMarketingIndexRouteImport.update({
    id: '/components/marketing/',
    path: '/components/marketing/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminContentPostsNewRoute = AdminContentPostsNewRouteImport.update({
  id: '/content/posts/new',
  path: '/content/posts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentPostsIdRoute = AdminContentPostsIdRouteImport.update({
  id: '/content/posts/$id',
  path: '/content/posts/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/admin/kb/$slug': typeof AdminKbSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/privacy-policy/': typeof LegalPrivacyPolicyIndexRoute
  '/about/': typeof PublicAboutIndexRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/contact/': typeof PublicContactIndexRoute
  '/portfolio/': typeof PublicPortfolioIndexRoute
  '/services/': typeof PublicServicesIndexRoute
  '/admin/components/': typeof AdminComponentsIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/docs/': typeof AdminDocsIndexRoute
  '/admin/kb/': typeof AdminKbIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/content/posts/$id': typeof AdminContentPostsIdRoute
  '/admin/content/posts/new': typeof AdminContentPostsNewRoute
  '/admin/components/marketing/': typeof AdminComponentsMarketingIndexRoute
  '/admin/components/navigation/': typeof AdminComponentsNavigationIndexRoute
  '/admin/components/ui/': typeof AdminComponentsUiIndexRoute
  '/admin/content/posts/': typeof AdminContentPostsIndexRoute
  '/admin/docs/adr/': typeof AdminDocsAdrIndexRoute
  '/admin/docs/architecture/': typeof AdminDocsArchitectureIndexRoute
  '/admin/docs/phases/': typeof AdminDocsPhasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/admin/kb/$slug': typeof AdminKbSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/privacy-policy': typeof LegalPrivacyPolicyIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/contact': typeof PublicContactIndexRoute
  '/portfolio': typeof PublicPortfolioIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/admin/components': typeof AdminComponentsIndexRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/docs': typeof AdminDocsIndexRoute
  '/admin/kb': typeof AdminKbIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/content/posts/$id': typeof AdminContentPostsIdRoute
  '/admin/content/posts/new': typeof AdminContentPostsNewRoute
  '/admin/components/marketing': typeof AdminComponentsMarketingIndexRoute
  '/admin/components/navigation': typeof AdminComponentsNavigationIndexRoute
  '/admin/components/ui': typeof AdminComponentsUiIndexRoute
  '/admin/content/posts': typeof AdminContentPostsIndexRoute
  '/admin/docs/adr': typeof AdminDocsAdrIndexRoute
  '/admin/docs/architecture': typeof AdminDocsArchitectureIndexRoute
  '/admin/docs/phases': typeof AdminDocsPhasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_legal': typeof LegalRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/admin/kb/$slug': typeof AdminKbSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/_legal/privacy-policy/': typeof LegalPrivacyPolicyIndexRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/contact/': typeof PublicContactIndexRoute
  '/_public/portfolio/': typeof PublicPortfolioIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
  '/admin/components/': typeof AdminComponentsIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/docs/': typeof AdminDocsIndexRoute
  '/admin/kb/': typeof AdminKbIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/content/posts/$id': typeof AdminContentPostsIdRoute
  '/admin/content/posts/new': typeof AdminContentPostsNewRoute
  '/admin/components/marketing/': typeof AdminComponentsMarketingIndexRoute
  '/admin/components/navigation/': typeof AdminComponentsNavigationIndexRoute
  '/admin/components/ui/': typeof AdminComponentsUiIndexRoute
  '/admin/content/posts/': typeof AdminContentPostsIndexRoute
  '/admin/docs/adr/': typeof AdminDocsAdrIndexRoute
  '/admin/docs/architecture/': typeof AdminDocsArchitectureIndexRoute
  '/admin/docs/phases/': typeof AdminDocsPhasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/admin/kb/$slug'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/signup/'
    | '/privacy-policy/'
    | '/about/'
    | '/blog/'
    | '/contact/'
    | '/portfolio/'
    | '/services/'
    | '/admin/components/'
    | '/admin/content/'
    | '/admin/dashboard/'
    | '/admin/docs/'
    | '/admin/kb/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/content/posts/$id'
    | '/admin/content/posts/new'
    | '/admin/components/marketing/'
    | '/admin/components/navigation/'
    | '/admin/components/ui/'
    | '/admin/content/posts/'
    | '/admin/docs/adr/'
    | '/admin/docs/architecture/'
    | '/admin/docs/phases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/admin/kb/$slug'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/privacy-policy'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/admin/components'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/docs'
    | '/admin/kb'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/content/posts/$id'
    | '/admin/content/posts/new'
    | '/admin/components/marketing'
    | '/admin/components/navigation'
    | '/admin/components/ui'
    | '/admin/content/posts'
    | '/admin/docs/adr'
    | '/admin/docs/architecture'
    | '/admin/docs/phases'
  id:
    | '__root__'
    | '/_auth'
    | '/_legal'
    | '/_public'
    | '/admin'
    | '/_public/'
    | '/admin/'
    | '/_public/blog/$slug'
    | '/_public/portfolio/$slug'
    | '/admin/kb/$slug'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/reset-password/'
    | '/_auth/signup/'
    | '/_legal/privacy-policy/'
    | '/_public/about/'
    | '/_public/blog/'
    | '/_public/contact/'
    | '/_public/portfolio/'
    | '/_public/services/'
    | '/admin/components/'
    | '/admin/content/'
    | '/admin/dashboard/'
    | '/admin/docs/'
    | '/admin/kb/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/content/posts/$id'
    | '/admin/content/posts/new'
    | '/admin/components/marketing/'
    | '/admin/components/navigation/'
    | '/admin/components/ui/'
    | '/admin/content/posts/'
    | '/admin/docs/adr/'
    | '/admin/docs/architecture/'
    | '/admin/docs/phases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kb/': {
      id: '/admin/kb/'
      path: '/kb'
      fullPath: '/admin/kb/'
      preLoaderRoute: typeof AdminKbIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/docs/': {
      id: '/admin/docs/'
      path: '/docs'
      fullPath: '/admin/docs/'
      preLoaderRoute: typeof AdminDocsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/components/': {
      id: '/admin/components/'
      path: '/components'
      fullPath: '/admin/components/'
      preLoaderRoute: typeof AdminComponentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/portfolio/': {
      id: '/_public/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PublicPortfolioIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact/': {
      id: '/_public/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof PublicContactIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PublicAboutIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_legal/privacy-policy/': {
      id: '/_legal/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof LegalPrivacyPolicyIndexRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kb/$slug': {
      id: '/admin/kb/$slug'
      path: '/kb/$slug'
      fullPath: '/admin/kb/$slug'
      preLoaderRoute: typeof AdminKbSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/portfolio/$slug': {
      id: '/_public/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PublicPortfolioSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/docs/phases/': {
      id: '/admin/docs/phases/'
      path: '/docs/phases'
      fullPath: '/admin/docs/phases/'
      preLoaderRoute: typeof AdminDocsPhasesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/docs/architecture/': {
      id: '/admin/docs/architecture/'
      path: '/docs/architecture'
      fullPath: '/admin/docs/architecture/'
      preLoaderRoute: typeof AdminDocsArchitectureIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/docs/adr/': {
      id: '/admin/docs/adr/'
      path: '/docs/adr'
      fullPath: '/admin/docs/adr/'
      preLoaderRoute: typeof AdminDocsAdrIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/posts/': {
      id: '/admin/content/posts/'
      path: '/content/posts'
      fullPath: '/admin/content/posts/'
      preLoaderRoute: typeof AdminContentPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/components/ui/': {
      id: '/admin/components/ui/'
      path: '/components/ui'
      fullPath: '/admin/components/ui/'
      preLoaderRoute: typeof AdminComponentsUiIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/components/navigation/': {
      id: '/admin/components/navigation/'
      path: '/components/navigation'
      fullPath: '/admin/components/navigation/'
      preLoaderRoute: typeof AdminComponentsNavigationIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/components/marketing/': {
      id: '/admin/components/marketing/'
      path: '/components/marketing'
      fullPath: '/admin/components/marketing/'
      preLoaderRoute: typeof AdminComponentsMarketingIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/posts/new': {
      id: '/admin/content/posts/new'
      path: '/content/posts/new'
      fullPath: '/admin/content/posts/new'
      preLoaderRoute: typeof AdminContentPostsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/posts/$id': {
      id: '/admin/content/posts/$id'
      path: '/content/posts/$id'
      fullPath: '/admin/content/posts/$id'
      preLoaderRoute: typeof AdminContentPostsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface LegalRouteRouteChildren {
  LegalPrivacyPolicyIndexRoute: typeof LegalPrivacyPolicyIndexRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalPrivacyPolicyIndexRoute: LegalPrivacyPolicyIndexRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicPortfolioSlugRoute: typeof PublicPortfolioSlugRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicContactIndexRoute: typeof PublicContactIndexRoute
  PublicPortfolioIndexRoute: typeof PublicPortfolioIndexRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicPortfolioSlugRoute: PublicPortfolioSlugRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicContactIndexRoute: PublicContactIndexRoute,
  PublicPortfolioIndexRoute: PublicPortfolioIndexRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminKbSlugRoute: typeof AdminKbSlugRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminComponentsIndexRoute: typeof AdminComponentsIndexRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDocsIndexRoute: typeof AdminDocsIndexRoute
  AdminKbIndexRoute: typeof AdminKbIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminContentPostsIdRoute: typeof AdminContentPostsIdRoute
  AdminContentPostsNewRoute: typeof AdminContentPostsNewRoute
  AdminComponentsMarketingIndexRoute: typeof AdminComponentsMarketingIndexRoute
  AdminComponentsNavigationIndexRoute: typeof AdminComponentsNavigationIndexRoute
  AdminComponentsUiIndexRoute: typeof AdminComponentsUiIndexRoute
  AdminContentPostsIndexRoute: typeof AdminContentPostsIndexRoute
  AdminDocsAdrIndexRoute: typeof AdminDocsAdrIndexRoute
  AdminDocsArchitectureIndexRoute: typeof AdminDocsArchitectureIndexRoute
  AdminDocsPhasesIndexRoute: typeof AdminDocsPhasesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminKbSlugRoute: AdminKbSlugRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminComponentsIndexRoute: AdminComponentsIndexRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDocsIndexRoute: AdminDocsIndexRoute,
  AdminKbIndexRoute: AdminKbIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminContentPostsIdRoute: AdminContentPostsIdRoute,
  AdminContentPostsNewRoute: AdminContentPostsNewRoute,
  AdminComponentsMarketingIndexRoute: AdminComponentsMarketingIndexRoute,
  AdminComponentsNavigationIndexRoute: AdminComponentsNavigationIndexRoute,
  AdminComponentsUiIndexRoute: AdminComponentsUiIndexRoute,
  AdminContentPostsIndexRoute: AdminContentPostsIndexRoute,
  AdminDocsAdrIndexRoute: AdminDocsAdrIndexRoute,
  AdminDocsArchitectureIndexRoute: AdminDocsArchitectureIndexRoute,
  AdminDocsPhasesIndexRoute: AdminDocsPhasesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
